# Generated by Django 6.1.1 on 2026-10-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATTENDED', 'Asistió'), ('JUSTIFIED', 'Ausencia justificada'), ('UNJUSTIFIED', 'Ausencia no justificada'), ('RECOVERED', 'Recuperada')], max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_session', 'student'), name='unique_attendance_per_class_student')],
            },
        ),
    ]
